name: Test Schaufel

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

defaults:
  run:
    shell: bash

env:
  LC_ALL: C.UTF-8

jobs:
  pr-test-ubuntu:
    name: "Test (${{ matrix.os }})"
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-22.04
          - ubuntu-24.04
          - ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Show runner info
        run: echo "Running on ${{ matrix.os }}"

      - name: Install build tools
        run: sudo apt-get update && sudo apt-get install -y build-essential autotools-dev clang

      - name: Install dependencies
        run: sudo apt-get install -y libhiredis-dev librdkafka-dev libconfig-dev libjson-c-dev libpq-dev

      - name: Configure
        run: autoreconf --force -i && ./configure

      - name: Run testsuite
        run: make test

      - name: Build
        run: make

      - name: Install
        run: sudo make install

      - name: Run ASAN test
        run: |
          make clean
          CC=clang LDFLAGS='-fsanitize=address -fno-omit-frame-pointer' CFLAGS='-Og -fsanitize=address -fno-omit-frame-pointer' ./configure
          make test
          make

      - name: Run functional test
        run: |
          src/schaufel -c 1 -i f -p 1 -o f -f src/main.c -F main.c
          diff -q src/main.c main.c

  pr-test-freebsd:
    name: Test Schaufel on FreeBSD
    runs-on: macos-12
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run FreeBSD test
        id: test
        uses: vmactions/freebsd-vm@v0
        with:
          usesh: true
          prepare: |
            # install dependencies
            pkg install -y autotools librdkafka hiredis json-c postgresql14-client libconfig
          run: |
            autoreconf --force -i
            ./configure
            make test
            make
            make install
            src/schaufel -c 1 -i f -p 1 -o f -f src/main.c -F main.c
            diff -q src/main.c main.c
